add_library(generalszh_status_definitions STATIC)
target_sources(generalszh_status_definitions PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES
	definitions/disabled_processing_definition.cppm)
target_compile_features(generalszh_status_definitions PUBLIC cxx_std_23)
set_property(TARGET generalszh_status_definitions PROPERTY CXX_SCAN_FOR_MODULES ON)

if(RTS_BUILD_ZEROHOUR_EXTRAS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set_source_files_properties(definitions/disabled_processing_definition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_disabled_processing_definition_tests definitions/disabled_processing_definition.test)
	set_property(TARGET generalszh_disabled_processing_definition_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_disabled_processing_definition_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_disabled_processing_definition_tests PRIVATE
		generalszh_status_definitions engine_jobs Boost::included_unit_test_framework)
	add_test(NAME generalszh_disabled_processing_definition_tests COMMAND generalszh_disabled_processing_definition_tests)
endif()
