cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "Pass an isolated -DTEST_ROOT=<temporary directory>")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef fixture_run)
set(TEST_ROOT "${TEST_ROOT}/${fixture_run}")
function(probe name path source expected)
    set(root "${TEST_ROOT}/${name}")
    get_filename_component(directory "${root}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${root}/${path}" "${source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT=${root}"
        -P "${CMAKE_CURRENT_LIST_DIR}/gameplay.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "pass")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: expected pass: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "${name}: expected ${expected}: ${output}${error}")
    endif()
endfunction()

set(component "engine/gameplay/common/health/components/health.cppm")
set(system "engine/gameplay/common/health/systems/health_system.cppm")
set(definition "engine/gameplay/rts/power/definitions/power_definition.cppm")
set(game "games/generalszh/gameplay/supply/systems/supply_system.cppm")

probe(component "${component}" "template<> struct ComponentTraits<Health> {};" pass)
probe(system "${system}" "struct HealthSystem { using Query = Q; };" pass)
probe(definition "${definition}" "struct PowerDefinition { int produced; };" pass)
probe(gamesystem "${game}" "struct SupplySystem {};" pass)
probe(resource "engine/gameplay/rts/power/resources/power_ledger.cppm" "struct PowerLedger {};" pass)

probe(badgenre "engine/gameplay/strategy/power/systems/x.cppm" "struct X {};" domain-layout)
probe(inputsfolder "engine/gameplay/rts/orders/inputs/order_batch.cppm" "struct OrderBatch {};" domain-layout)
probe(nested "engine/gameplay/common/combat/damage/systems/x.cppm" "struct X {};" domain-layout)
probe(domainroot "engine/gameplay/common/health/health.cppm" "export import a;" domain-layout)
probe(gamenested "games/generalszh/gameplay/production/doors/components/door.cppm" "struct Door {};" domain-layout)

probe(componentinsystems "${system}" "template<> struct ComponentTraits<Health> {};" component-outside-components)
probe(systemincomponents "${component}" "struct HealthSystem {};" system-outside-systems)
probe(wrapper "${system}" "class HealthSystems {};" feature-wrapper)
probe(simulation "games/generalszh/session/x.cppm" "class PowerSimulation {};" feature-wrapper)

probe(scheduler "${system}" "class Facade { ecs::Scheduler scheduler; };" execution-owner)
probe(registry "${system}" "std::unique_ptr<ecs::SystemRegistry> registry;" execution-owner)
probe(helper "${system}" "inline void RegisterHealthSystems(ecs::SystemRegistry &registry, HealthSystem &system) { registry.Register(system); }" pass)
probe(root "games/generalszh/session/game_session.cppm" "class GameSession { ecs::Scheduler scheduler; ecs::SystemRegistry registry; };" pass)

probe(engineimport "engine/ecs/x.cppm" "export import games.generalszh.session;" engine-game-import)
probe(comments "${system}" "// class OldSystems {};\n/* ecs::Scheduler x; */\nstruct HealthSystem {};" pass)
# Presentation is ECS too: no stateful directors or entity-keyed maps outside the recorded debt.
probe(presentation_director "games/generalszh/presentation/audio/sound_director.cppm" "class SoundDirector { };" "presentation-object-style")
probe(presentation_entity_map "games/generalszh/hosts/game/view.cpp" "std::unordered_map<std::uint64_t, Look> looks;" "presentation-object-style")
probe(presentation_system "games/generalszh/presentation/objects/systems/look_systems.cppm" "struct LookSystem { using Query = Q; };" pass)
message(STATUS "Gameplay architecture checker self-tests passed")
