cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "Pass an isolated -DTEST_ROOT=<temporary directory>")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef fixture_run)
set(TEST_ROOT "${TEST_ROOT}/${fixture_run}")
# probe(name path source expected [debt entries...])
function(probe name path source expected)
    set(root "${TEST_ROOT}/${name}")
    get_filename_component(directory "${root}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${root}/${path}" "${source}")
    set(debt "")
    foreach(entry IN LISTS ARGN)
        string(APPEND debt " \"${entry}\"")
    endforeach()
    file(WRITE "${root}/debt.cmake" "set(modern_code_debt${debt})\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT=${root}"
        "-DMODERN_CODE_DEBT_FILE=${root}/debt.cmake"
        -P "${CMAKE_CURRENT_LIST_DIR}/modern_code.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "pass")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: expected pass: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "${name}: expected ${expected}: ${output}${error}")
    endif()
endfunction()

set(sim "engine/gameplay/common/health/systems/health_system.cppm")
probe(clean "${sim}" "export module x;\nstruct HealthSystem { std::int64_t value; };" pass)
probe(legacyinclude "${sim}" "#include \"Common/GameType.h\"\n" legacy-include)
probe(wwvegas "games/generalszh/session/x.cppm" "#include <WWVegas/WWLib/always.h>\n" legacy-include)
probe(legacytype "${sim}" "struct A { Real speed; };" legacy-type)
probe(coord "${sim}" "Coord3D position;" legacy-type)
probe(typeinstring "${sim}" "constexpr auto name = \"Real\";" pass)
probe(typeincomment "${sim}" "// Real was the legacy float\nstruct A {};" pass)
probe(byte "${sim}" "static void Byte(int);" pass)
probe(float "${sim}" "struct A { float speed; };" float)
probe(double "engine/ecs/core/x.cppm" "double Delta();" float)
probe(floatinstring "${sim}" "auto s = \"float\";" pass)
probe(floatword "${sim}" "struct Floating {}; int floatValue;" pass)
probe(presentation "games/generalszh/presentation/model/x.cppm" "float alpha;" pass)
probe(presentation_content "games/renegade/content/presentation/style.cppm" "float font_scale;" pass)
probe(simulation_content "games/renegade/content/armor/catalog.cppm" "float damage;" float)
probe(presentation_content_platform "games/renegade/content/presentation/style.cppm" "void x() { LoadLibrary(0); }" native-platform)
probe(outofscope "engine/graphics/x.cppm" "float alpha; Real legacy;" pass)
probe(thenaming "${sim}" "extern GlobalData *TheGlobalData;" the-naming)
probe(theword "${sim}" "int Theme; int Theory;" pass)
probe(singleton "${sim}" "class Registry { public: static Registry& Instance(); };" singleton)
probe(getinstance "${sim}" "class Registry { static Registry *GetInstance() noexcept; };" singleton)
probe(instancemember "${sim}" "struct A { int Instance(); };" pass)
probe(commonimportsrts "${sim}" "export module x;\nimport engine.gameplay.rts.power.components.power;" genre-dependency)
probe(rtsimportsfps "engine/gameplay/rts/power/systems/x.cppm" "export import engine.gameplay.fps.weapons.x;" genre-dependency)
probe(fpsimportsrts "engine/gameplay/fps/weapons/systems/x.cppm" "import engine.gameplay.rts.orders.x;" genre-dependency)
probe(rtsimportscommon "engine/gameplay/rts/power/systems/x.cppm" "import engine.gameplay.common.health.components.health;" pass)
probe(gameimportsrts "games/generalszh/gameplay/power/systems/x.cppm" "import engine.gameplay.rts.power.components.power;" pass)
probe(getworld "${sim}" "void Execute(SystemContext &context) { context.GetWorld().Get<Health>(e); }" world-access)
probe(enginecoreworld "engine/ecs/system/x.cppm" "World &GetWorld() const noexcept;" pass)
probe(debtallowed "${sim}" "float speed;" pass "${sim}|float")
probe(debtresolved "${sim}" "int speed;" resolved-debt "${sim}|float")
message(STATUS "Modern code policy checker self-tests passed")
probe(renegade_float "games/renegade/gameplay/defense/algorithms/x.cppm" "float damage;" float)
probe(renegade_module_only "games/renegade/hosts/game/main.cpp" "int main() {}" module-only)
probe(renegade_modules "games/renegade/session/x.cppm" "export module games.renegade.session; import std;" pass)
probe(renegade_windows "games/renegade/hosts/game/main.cppm" "#include <windows.h>\n" native-platform)
probe(renegade_sdl "games/renegade/hosts/game/main.cppm" "SDL_PollEvent(&event);" native-platform)
probe(renegade_dll "games/renegade/hosts/game/main.cppm" "__declspec(dllimport) void Function();" native-platform)
probe(w3d_platform "engine/gui/w3d/view.cppm" "#include <SDL3/SDL.h>\n" native-platform)
probe(w3d_presentation "engine/gui/w3d/view.cppm" "export module engine.gui.w3d.view; struct Rect { float x; };" pass)
probe(renegade_shared_platform "games/renegade/hosts/game/main.cppm" "import engine.platform.adapters.sdl3; engine::platform::sdl3::SDL3PlatformAdapter platform;" pass)
