add_library(generalszh_model_conditions STATIC)
target_sources(generalszh_model_conditions PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES model_condition.cppm pending_conditions.cppm)
target_link_libraries(generalszh_model_conditions PUBLIC engine_ecs)
target_compile_features(generalszh_model_conditions PUBLIC cxx_std_23)
set_property(TARGET generalszh_model_conditions PROPERTY CXX_SCAN_FOR_MODULES ON)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set_source_files_properties(model_condition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_model_condition_tests model_condition.test)
	set_property(TARGET generalszh_model_condition_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_model_condition_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_model_condition_tests PRIVATE generalszh_model_conditions Boost::included_unit_test_framework)
	add_test(NAME generalszh_model_condition_tests COMMAND generalszh_model_condition_tests)
	set_source_files_properties(pending_conditions.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_pending_conditions_tests pending_conditions.test)
	set_property(TARGET generalszh_pending_conditions_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_pending_conditions_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_pending_conditions_tests PRIVATE generalszh_model_conditions Boost::included_unit_test_framework)
	add_test(NAME generalszh_pending_conditions_tests COMMAND generalszh_pending_conditions_tests)
endif()
