add_library(generalszh_production_definition_adapter STATIC)
target_sources(generalszh_production_definition_adapter PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES
	production_definition.cppm presentation_definition.cppm disabled_processing_definition.cppm)
target_compile_features(generalszh_production_definition_adapter PUBLIC cxx_std_23)
set_property(TARGET generalszh_production_definition_adapter PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_production_definition_adapter PUBLIC generalszh_production_rules generalszh_status_definitions)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set_source_files_properties(production_definition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_production_definition_adapter_tests production_definition.test)
	set_property(TARGET generalszh_production_definition_adapter_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_production_definition_adapter_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_production_definition_adapter_tests PRIVATE generalszh_production_definition_adapter Boost::included_unit_test_framework)
	add_test(NAME generalszh_production_definition_adapter_tests COMMAND generalszh_production_definition_adapter_tests)
	set_source_files_properties(presentation_definition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_presentation_definition_adapter_tests presentation_definition.test)
	set_property(TARGET generalszh_presentation_definition_adapter_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_presentation_definition_adapter_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_presentation_definition_adapter_tests PRIVATE generalszh_production_definition_adapter Boost::included_unit_test_framework)
	add_test(NAME generalszh_presentation_definition_adapter_tests COMMAND generalszh_presentation_definition_adapter_tests)
	set_source_files_properties(disabled_processing_definition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_disabled_processing_adapter_tests disabled_processing_definition.test)
	set_property(TARGET generalszh_disabled_processing_adapter_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_disabled_processing_adapter_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_disabled_processing_adapter_tests PRIVATE generalszh_production_definition_adapter Boost::included_unit_test_framework)
	add_test(NAME generalszh_disabled_processing_adapter_tests COMMAND generalszh_disabled_processing_adapter_tests)
endif()
