add_library(generalszh_economy_presentation STATIC)
target_sources(generalszh_economy_presentation PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES transaction_sound.cppm)
target_compile_features(generalszh_economy_presentation PUBLIC cxx_std_23)
set_property(TARGET generalszh_economy_presentation PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_economy_presentation PUBLIC engine_events)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set_source_files_properties(transaction_sound.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_economy_presentation_tests transaction_sound.test)
	set_property(TARGET generalszh_economy_presentation_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_economy_presentation_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_economy_presentation_tests PRIVATE generalszh_economy_presentation Boost::included_unit_test_framework)
	add_test(NAME generalszh_economy_presentation_tests COMMAND generalszh_economy_presentation_tests)
endif()
