add_library(generalszh_rank_content STATIC)
target_sources(generalszh_rank_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES rank_definition.cppm)
target_compile_features(generalszh_rank_content PUBLIC cxx_std_23)
set_property(TARGET generalszh_rank_content PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_rank_content PUBLIC generalszh_content_ini engine_gameplay_rts_rank)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set_source_files_properties(rank_definition.test PROPERTIES LANGUAGE CXX)
	add_executable(generalszh_rank_content_tests rank_definition.test)
	set_property(TARGET generalszh_rank_content_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(generalszh_rank_content_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(generalszh_rank_content_tests PRIVATE generalszh_rank_content Boost::included_unit_test_framework)
	add_test(NAME generalszh_rank_content_tests COMMAND generalszh_rank_content_tests)
endif()
