#!/usr/bin/env python3
"""Generates content/objects/kind_of.cppm from the legacy KindOf name table (read-only)."""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[4]
source = (root / "GeneralsMD/Code/GameEngine/Source/Common/System/KindOf.cpp").read_text(encoding="latin-1")
body = re.search(r"s_bitNameList\[\]\s*=\s*\{(.*?)\};", source, re.S).group(1)
body = re.sub(r"//[^\n]*", "", body)
names = [n for n in re.findall(r'"([A-Z0-9_]+)"', body)]
rows = "\n".join(f'\t"{name}",' for name in names)
out = f"""// Generated by content/tools/generate_kind_of.py from the original KindOf table. Do not edit.
module;
#include <array>
#include <cstdint>
#include <string_view>

export module games.generalszh.content.objects.kind_of;

export namespace generalszh::content
{{
// Object categories ("KindOf" flags); bit index = position in this table.
inline constexpr std::array<std::string_view, {len(names)}> KindOfNames{{
{rows}
}};

inline constexpr std::size_t KindOfWords = ({len(names)} + 63) / 64;
using KindOfMask = std::array<std::uint64_t, KindOfWords>;

constexpr bool HasKindOf(const KindOfMask &mask, std::size_t bit) noexcept
{{
	return (mask[bit / 64] >> (bit % 64)) & 1u;
}}

constexpr std::size_t KindOfBit(std::string_view name) noexcept
{{
	for (std::size_t index = 0; index < KindOfNames.size(); ++index)
		if (KindOfNames[index] == name)
			return index;
	return KindOfNames.size();
}}
}}
"""
(root / "games/generalszh/content/objects/kind_of.cppm").write_text(out, newline="\n")
print(len(names), "kinds")
