add_library(generalszh_capture_content STATIC)
target_sources(generalszh_capture_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES capture_definition.cppm)
target_compile_features(generalszh_capture_content PUBLIC cxx_std_23)
target_link_libraries(generalszh_capture_content PUBLIC generalszh_content_ini generalszh_capture_definitions generalszh_upgrade_content)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set_source_files_properties(capture_definition.test PROPERTIES LANGUAGE CXX)
    add_executable(generalszh_capture_content_tests capture_definition.test)
    target_link_libraries(generalszh_capture_content_tests PRIVATE generalszh_capture_content generalszh_game_session Boost::included_unit_test_framework)
    add_test(NAME generalszh_capture_content_tests COMMAND generalszh_capture_content_tests)
endif()
