export module games.generalszh.session.composition.simulation;
import std;

export import engine.ecs.core.world;
export import engine.ecs.system.system;
export import games.generalszh.session.composition.simulation_setup;
export import games.generalszh.session.composition.abilities;
export import games.generalszh.session.composition.ai;
export import games.generalszh.session.composition.aircraft;
export import games.generalszh.session.composition.appearance;
export import games.generalszh.session.composition.areas;
export import games.generalszh.session.composition.battleplans;
export import games.generalszh.session.composition.blocking;
export import games.generalszh.session.composition.bridges;
export import games.generalszh.session.composition.collision;
export import games.generalszh.session.composition.combat;
export import games.generalszh.session.composition.combat_drop;
export import games.generalszh.session.composition.construction;
export import games.generalszh.session.composition.containment;
export import games.generalszh.session.composition.crates;
export import games.generalszh.session.composition.creation;
export import games.generalszh.session.composition.death;
export import games.generalszh.session.composition.delivery;
export import games.generalszh.session.composition.docking;
export import games.generalszh.session.composition.economy;
export import games.generalszh.session.composition.effects;
export import games.generalszh.session.composition.emp;
export import games.generalszh.session.composition.fire;
export import games.generalszh.session.composition.flight_deck;
export import games.generalszh.session.composition.hacking;
export import games.generalszh.session.composition.harvesting;
export import games.generalszh.session.composition.healing;
export import games.generalszh.session.composition.health;
export import games.generalszh.session.composition.horde;
export import games.generalszh.session.composition.identity;
export import games.generalszh.session.composition.lifecycle;
export import games.generalszh.session.composition.lifetime;
export import games.generalszh.session.composition.loadout;
export import games.generalszh.session.composition.match;
export import games.generalszh.session.composition.mines;
export import games.generalszh.session.composition.movement;
export import games.generalszh.session.composition.navigation;
export import games.generalszh.session.composition.parachute;
export import games.generalszh.session.composition.physics;
export import games.generalszh.session.composition.poison;
export import games.generalszh.session.composition.powers;
export import games.generalszh.session.composition.production;
export import games.generalszh.session.composition.propaganda;
export import games.generalszh.session.composition.radar;
export import games.generalszh.session.composition.railroad;
export import games.generalszh.session.composition.scripts;
export import games.generalszh.session.composition.slaves;
export import games.generalszh.session.composition.spatial;
export import games.generalszh.session.composition.status;
export import games.generalszh.session.composition.stealth;
export import games.generalszh.session.composition.teams;
export import games.generalszh.session.composition.topple;
export import games.generalszh.session.composition.wave_guides;
export import games.generalszh.session.composition.upgrades;
export import games.generalszh.session.composition.veterancy;
export import games.generalszh.session.composition.vision;
export import games.generalszh.session.composition.weapons;
export import games.generalszh.session.composition.world;

// The simulation composed from its domains (session/composition): each domain's components registered with the world
// (with the presentation's side tables riding on the same entities), the components finalized, each domain's
// resources emplaced, each domain's systems registered with the tick's schedule, then the order between them, each
// domain stating what its systems run after.
export namespace generalszh::session::composition
{
inline void ComposeSimulation(ecs::World &world, ecs::SystemRegistry &registry, const SimulationSetup &setup,
	const std::function<void(ecs::World &)> &presentationComponents)
{
	RegisterSpatialComponents(world);
	RegisterIdentityComponents(world);
	RegisterPowersComponents(world);
	RegisterDeathComponents(world);
	RegisterContainmentComponents(world);
	RegisterRadarComponents(world);
	RegisterVisionComponents(world);
	RegisterHealthComponents(world);
	RegisterConstructionComponents(world);
	RegisterAbilitiesComponents(world);
	RegisterAiComponents(world);
	RegisterCombatComponents(world);
	RegisterAppearanceComponents(world);
	RegisterScriptsComponents(world);
	RegisterWorldComponents(world);
	RegisterMovementComponents(world);
	RegisterStatusComponents(world);
	RegisterProductionComponents(world);
	RegisterNavigationComponents(world);
	RegisterPoisonComponents(world);
	RegisterBridgesComponents(world);
	RegisterHackingComponents(world);
	RegisterBattleplansComponents(world);
	RegisterCratesComponents(world);
	RegisterEconomyComponents(world);
	RegisterStealthComponents(world);
	RegisterCreationComponents(world);
	RegisterEffectsComponents(world);
	RegisterRailroadComponents(world);
	RegisterCombatDropComponents(world);
	RegisterFlightDeckComponents(world);
	RegisterAircraftComponents(world);
	RegisterWeaponsComponents(world);
	RegisterUpgradesComponents(world);
	RegisterVeterancyComponents(world);
	RegisterHordeComponents(world);
	RegisterSlavesComponents(world);
	RegisterParachuteComponents(world);
	RegisterMatchComponents(world);
	RegisterCollisionComponents(world);
	RegisterBlockingComponents(world);
	RegisterTeamsComponents(world);
	RegisterDeliveryComponents(world);
	RegisterPhysicsComponents(world);
	RegisterLifetimeComponents(world);
	RegisterHealingComponents(world);
	RegisterFireComponents(world);
	RegisterPropagandaComponents(world);
	RegisterMinesComponents(world);
	RegisterEmpComponents(world);
	RegisterAreasComponents(world);
	RegisterToppleComponents(world);
	RegisterWaveGuidesComponents(world);
	RegisterDockingComponents(world);
	RegisterHarvestingComponents(world);
	RegisterLoadoutComponents(world);
	if (presentationComponents)
		presentationComponents(world);
	world.FinalizeComponents();
	EmplaceAbilitiesResources(world, setup);
	EmplaceAiResources(world, setup);
	EmplaceAircraftResources(world, setup);
	EmplaceAppearanceResources(world, setup);
	EmplaceBattleplansResources(world, setup);
	EmplaceBridgesResources(world, setup);
	EmplaceCollisionResources(world, setup);
	EmplaceBlockingResources(world, setup);
	EmplaceCombatResources(world, setup);
	EmplaceCombatDropResources(world, setup);
	EmplaceConstructionResources(world, setup);
	EmplaceContainmentResources(world, setup);
	EmplaceCratesResources(world, setup);
	EmplaceCreationResources(world, setup);
	EmplaceDeathResources(world, setup);
	EmplaceDeliveryResources(world, setup);
	EmplaceDockingResources(world, setup);
	EmplaceEconomyResources(world, setup);
	EmplaceEffectsResources(world, setup);
	EmplaceEmpResources(world, setup);
	EmplaceFireResources(world, setup);
	EmplaceFlightDeckResources(world, setup);
	EmplaceHackingResources(world, setup);
	EmplaceHarvestingResources(world, setup);
	EmplaceHealingResources(world, setup);
	EmplaceHealthResources(world, setup);
	EmplaceLifecycleResources(world, setup);
	EmplaceLifetimeResources(world, setup);
	EmplaceLoadoutResources(world, setup);
	EmplaceMinesResources(world, setup);
	EmplaceMovementResources(world, setup);
	EmplaceParachuteResources(world, setup);
	EmplacePhysicsResources(world, setup);
	EmplacePowersResources(world, setup);
	EmplaceProductionResources(world, setup);
	EmplacePropagandaResources(world, setup);
	EmplaceRadarResources(world, setup);
	EmplaceSlavesResources(world, setup);
	EmplaceSpatialResources(world, setup);
	EmplaceStatusResources(world, setup);
	EmplaceStealthResources(world, setup);
	EmplaceToppleResources(world, setup);
	EmplaceWaveGuidesResources(world, setup);
	EmplaceVeterancyResources(world, setup);
	EmplaceVisionResources(world, setup);
	EmplaceWorldResources(world, setup);
	RegisterPhysicsSystems(registry);
	RegisterContainmentSystems(registry);
	RegisterPowersSystems(registry);
	RegisterRadarSystems(registry);
	RegisterVisionSystems(registry);
	RegisterDeathSystems(registry);
	RegisterAircraftSystems(registry);
	RegisterSpatialSystems(registry);
	RegisterCombatSystems(registry);
	RegisterMovementSystems(registry);
	RegisterDeliverySystems(registry);
	RegisterNavigationSystems(registry);
	RegisterUpgradesSystems(registry);
	RegisterProductionSystems(registry);
	RegisterSlavesSystems(registry);
	RegisterHealthSystems(registry);
	RegisterVeterancySystems(registry);
	RegisterHordeSystems(registry);
	RegisterLifetimeSystems(registry);
	RegisterHealingSystems(registry);
	RegisterFireSystems(registry);
	RegisterStealthSystems(registry);
	RegisterParachuteSystems(registry);
	RegisterCratesSystems(registry);
	RegisterAbilitiesSystems(registry);
	RegisterBridgesSystems(registry);
	RegisterHackingSystems(registry);
	RegisterBattleplansSystems(registry);
	RegisterEconomySystems(registry);
	RegisterCreationSystems(registry);
	RegisterEffectsSystems(registry);
	RegisterRailroadSystems(registry);
	RegisterCombatDropSystems(registry);
	RegisterFlightDeckSystems(registry);
	RegisterWeaponsSystems(registry);
	RegisterAiSystems(registry);
	RegisterCollisionSystems(registry);
	RegisterBlockingSystems(registry);
	RegisterTeamsSystems(registry);
	RegisterToppleSystems(registry);
	RegisterWaveGuidesSystems(registry);
	RegisterPropagandaSystems(registry);
	RegisterMinesSystems(registry);
	RegisterEmpSystems(registry);
	RegisterAreasSystems(registry);
	RegisterStatusSystems(registry);
	RegisterConstructionSystems(registry);
	RegisterLoadoutSystems(registry);
	RegisterHarvestingSystems(registry);
	RegisterDockingSystems(registry);
	RegisterMatchSystems(registry);
	RegisterLifecycleSystems(registry);
	RegisterAppearanceSystems(registry);
	RegisterPoisonSystems(registry);
	OrderContainmentSystems(registry);
	OrderCombatSystems(registry);
	OrderHealthSystems(registry);
	OrderPhysicsSystems(registry);
	OrderVisionSystems(registry);
	OrderSpatialSystems(registry);
	OrderMovementSystems(registry);
	OrderDeliverySystems(registry);
	OrderAircraftSystems(registry);
	OrderLifecycleSystems(registry);
	OrderAppearanceSystems(registry);
	OrderSlavesSystems(registry);
	OrderHealingSystems(registry);
	OrderConstructionSystems(registry);
	OrderPropagandaSystems(registry);
	OrderProductionSystems(registry);
	OrderVeterancySystems(registry);
	OrderDeathSystems(registry);
	OrderCombatDropSystems(registry);
	OrderFlightDeckSystems(registry);
	OrderRailroadSystems(registry);
	OrderCreationSystems(registry);
	OrderAiSystems(registry);
	OrderEffectsSystems(registry);
	OrderWeaponsSystems(registry);
	OrderEconomySystems(registry);
	OrderCratesSystems(registry);
	OrderBattleplansSystems(registry);
	OrderDockingSystems(registry);
	OrderBridgesSystems(registry);
	OrderAbilitiesSystems(registry);
	OrderHarvestingSystems(registry);
	OrderCollisionSystems(registry);
	OrderBlockingSystems(registry);
	OrderTeamsSystems(registry);
	OrderParachuteSystems(registry);
	OrderStealthSystems(registry);
	OrderLoadoutSystems(registry);
	OrderMinesSystems(registry);
	OrderHordeSystems(registry);
	OrderPowersSystems(registry);
	OrderEmpSystems(registry);
	OrderMatchSystems(registry);
	OrderToppleSystems(registry);
	OrderWaveGuidesSystems(registry);
	OrderLifetimeSystems(registry);
	OrderFireSystems(registry);
	OrderPoisonSystems(registry);
}
}
