add_library(generalszh_sale_content STATIC)
target_sources(generalszh_sale_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES sale_definition.cppm)
target_compile_features(generalszh_sale_content PUBLIC cxx_std_23)
set_property(TARGET generalszh_sale_content PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_sale_content PUBLIC generalszh_building_content generalszh_selling)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set_source_files_properties(sale_definition.test PROPERTIES LANGUAGE CXX)
    add_executable(generalszh_sale_content_tests sale_definition.test)
    set_property(TARGET generalszh_sale_content_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
    target_link_libraries(generalszh_sale_content_tests PRIVATE generalszh_sale_content generalszh_game_session Boost::included_unit_test_framework)
    add_test(NAME generalszh_sale_content_tests COMMAND generalszh_sale_content_tests)
endif()
