cmake_minimum_required(VERSION 3.28)
# Standalone provisioning only; never download tools from project configure.
# Explicit host denotes the machine running the compiler, not a cross target.
if(NOT DEFINED ENGINE_HOST OR NOT IS_ABSOLUTE "${ENGINE_TOOLS_DIR}")
    message(FATAL_ERROR "Supply -DENGINE_HOST=<os-arch> and an absolute -DENGINE_TOOLS_DIR=<dedicated-directory>")
endif()
file(TO_CMAKE_PATH "${ENGINE_TOOLS_DIR}" ENGINE_TOOLS_DIR)
file(READ "${CMAKE_CURRENT_LIST_DIR}/lock.json" lock)
string(JSON host ERROR_VARIABLE host_error GET "${lock}" hosts "${ENGINE_HOST}")
if(host_error)
    message(FATAL_ERROR "No pinned binary package for host '${ENGINE_HOST}'. Do not substitute a different compiler version.")
endif()
file(MAKE_DIRECTORY "${ENGINE_TOOLS_DIR}")
file(LOCK "${ENGINE_TOOLS_DIR}/bootstrap.lock" GUARD PROCESS TIMEOUT 0)
foreach(tool llvm cmake ninja)
    string(JSON url GET "${host}" ${tool} url)
    string(JSON digest GET "${host}" ${tool} sha256)
    string(JSON prefix GET "${host}" ${tool} prefix)
    set(archive "${ENGINE_TOOLS_DIR}/${tool}.archive")
    set(destination "${ENGINE_TOOLS_DIR}/${tool}-${digest}")
    if(NOT EXISTS "${destination}/.complete")
        message(STATUS "Downloading/verifying ${tool} for ${ENGINE_HOST}")
        file(DOWNLOAD "${url}" "${archive}" EXPECTED_HASH "SHA256=${digest}"
            TLS_VERIFY ON STATUS download_status)
        list(GET download_status 0 download_code)
        if(NOT download_code EQUAL 0)
            message(FATAL_ERROR "${tool} download failed: ${download_status}")
        endif()
        file(MAKE_DIRECTORY "${destination}")
        if(tool STREQUAL "llvm")
            # Full LLVM includes unrelated backends/tools and large static
            # development libraries. Extract the compiler/scanner/link tools,
            # resource headers, STL headers and shared runtime dependencies.
            if(ENGINE_HOST MATCHES "^windows-")
                set(runtime_patterns "*/bin/*.dll")
            elseif(ENGINE_HOST MATCHES "^macos-")
                set(runtime_patterns "*/include/c++/*" "*/lib/*.dylib")
            else()
                set(runtime_patterns "*/include/c++/*" "*/lib/*.so*")
            endif()
            file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${destination}"
                PATTERNS "*/bin/clang*" "*/bin/llvm-ar*" "*/bin/llvm-ranlib*"
                "*/bin/llvm-lib*" "*/bin/lld*" "*/bin/ld.lld*" "*/bin/llvm-mt*"
                "*/bin/llvm-rc*" "*/lib/clang/*" ${runtime_patterns})
        else()
            file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${destination}")
        endif()
        file(WRITE "${destination}/.complete" "${digest}\n")
    endif()
    set(${tool}_root "${destination}/${prefix}")
endforeach()
if(ENGINE_HOST MATCHES "^windows-")
    set(exe ".exe")
else()
    set(exe "")
endif()
file(WRITE "${ENGINE_TOOLS_DIR}/environment.json"
    "{\n  \"ENGINE_LLVM_ROOT\": \"${llvm_root}\",\n  \"ENGINE_NINJA\": \"${ninja_root}/ninja${exe}\",\n  \"ENGINE_CMAKE_BIN\": \"${cmake_root}/bin\"\n}\n")
message(STATUS "Tool paths: ${ENGINE_TOOLS_DIR}/environment.json (no system installation or PATH changes)")
