add_library(generalszh_content_armor STATIC)
target_sources(generalszh_content_armor PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES armor_definition.cppm)
target_compile_features(generalszh_content_armor PUBLIC cxx_std_23)
target_link_libraries(generalszh_content_armor PUBLIC engine_gameplay_damage generalszh_content_ini)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set_source_files_properties(armor_definition.test PROPERTIES LANGUAGE CXX)
    add_executable(generalszh_content_armor_tests armor_definition.test)
    target_compile_definitions(generalszh_content_armor_tests PRIVATE BOOST_TEST_INCLUDED)
    target_link_libraries(generalszh_content_armor_tests PRIVATE generalszh_content_armor Boost::included_unit_test_framework)
    add_test(NAME generalszh_content_armor_tests COMMAND generalszh_content_armor_tests)
endif()
