add_library(engine_gameplay_regeneration STATIC)
target_sources(engine_gameplay_regeneration PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES
    definitions/regeneration_definition.cppm components/regeneration.cppm systems/regeneration_system.cppm)
target_compile_features(engine_gameplay_regeneration PUBLIC cxx_std_23)
target_link_libraries(engine_gameplay_regeneration PUBLIC engine_gameplay_combat)
if(ENGINE_GAMEPLAY_BUILD_TESTS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set(regeneration_tests definitions/regeneration_definition.test components/regeneration.test systems/regeneration_system.test)
    set_source_files_properties(${regeneration_tests} PROPERTIES LANGUAGE CXX)
    add_executable(engine_gameplay_regeneration_tests ${regeneration_tests})
    target_compile_definitions(engine_gameplay_regeneration_tests PRIVATE BOOST_TEST_INCLUDED)
    target_link_libraries(engine_gameplay_regeneration_tests PRIVATE engine_gameplay_regeneration Boost::included_unit_test_framework)
    add_test(NAME engine_gameplay_regeneration_tests COMMAND engine_gameplay_regeneration_tests)
endif()
