add_library(generalszh_progression_content STATIC)
target_sources(generalszh_progression_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES veterancy_decoder.cppm)
target_compile_features(generalszh_progression_content PUBLIC cxx_std_23)
set_property(TARGET generalszh_progression_content PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_progression_content PUBLIC generalszh_progression generalszh_content_ini)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
 find_package(boost_included_unit_test_framework CONFIG REQUIRED)
 set_source_files_properties(veterancy_decoder.test PROPERTIES LANGUAGE CXX)
 add_executable(generalszh_progression_content_tests veterancy_decoder.test)
 set_property(TARGET generalszh_progression_content_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
 target_compile_definitions(generalszh_progression_content_tests PRIVATE BOOST_TEST_INCLUDED)
 target_link_libraries(generalszh_progression_content_tests PRIVATE generalszh_progression_content Boost::included_unit_test_framework)
 add_test(NAME generalszh_progression_content_tests COMMAND generalszh_progression_content_tests)
endif()
