export module games.generalszh.content.objects.module_interfaces;
import std;

// Each module type's interfaces (ModuleFactory::findModuleInterfaceMask: the class's getInterfaceMask(), registered by
// ModuleFactory::init and W3DModuleFactory::init) and whether its module data is an AI's (ModuleData::isAiModuleData:
// AIUpdateModuleData and what derives from it, FlightDeckBehaviorModuleData among them). Generated from the original's
// headers; the template composition rules (ModuleInfo::clearCopiedFromDefaultEntries, clearAiModuleInfo) read them.
export namespace generalszh::content
{
namespace module_interface
{
inline constexpr std::uint32_t Update = 0x001u;       // MODULEINTERFACE_UPDATE
inline constexpr std::uint32_t Die = 0x002u;          // MODULEINTERFACE_DIE
inline constexpr std::uint32_t Damage = 0x004u;       // MODULEINTERFACE_DAMAGE
inline constexpr std::uint32_t Create = 0x008u;       // MODULEINTERFACE_CREATE
inline constexpr std::uint32_t Collide = 0x010u;      // MODULEINTERFACE_COLLIDE
inline constexpr std::uint32_t Body = 0x020u;         // MODULEINTERFACE_BODY
inline constexpr std::uint32_t Contain = 0x040u;      // MODULEINTERFACE_CONTAIN
inline constexpr std::uint32_t Upgrade = 0x080u;      // MODULEINTERFACE_UPGRADE
inline constexpr std::uint32_t SpecialPower = 0x100u; // MODULEINTERFACE_SPECIAL_POWER
inline constexpr std::uint32_t Destroy = 0x200u;      // MODULEINTERFACE_DESTROY
inline constexpr std::uint32_t Draw = 0x400u;         // MODULEINTERFACE_DRAW
inline constexpr std::uint32_t ClientUpdate = 0x800u; // MODULEINTERFACE_CLIENT_UPDATE
}

struct ModuleInterfaces
{
	std::string_view type;
	std::uint32_t mask{0};
	bool ai{false};
};

// Sorted by name (byte order) for the lookup.
inline constexpr ModuleInterfaces ModuleInterfaceTable[] = {
	{"AIUpdateInterface", 0x001u, true},
	{"ActiveBody", 0x020u, false},
	{"ActiveShroudUpgrade", 0x080u, false},
	{"AnimatedParticleSysBoneClientUpdate", 0x800u, false},
	{"AnimationSteeringUpdate", 0x001u, false},
	{"ArmorUpgrade", 0x080u, false},
	{"AssaultTransportAIUpdate", 0x001u, true},
	{"AssistedTargetingUpdate", 0x001u, false},
	{"AutoDepositUpdate", 0x001u, false},
	{"AutoFindHealingUpdate", 0x001u, false},
	{"AutoHealBehavior", 0x085u, false},
	{"BaikonurLaunchPower", 0x100u, false},
	{"BaseRegenerateUpdate", 0x005u, false},
	{"BattleBusSlowDeathBehavior", 0x003u, false},
	{"BattlePlanUpdate", 0x001u, false},
	{"BeaconClientUpdate", 0x800u, false},
	{"BoneFXDamage", 0x004u, false},
	{"BoneFXUpdate", 0x001u, false},
	{"BridgeBehavior", 0x007u, false},
	{"BridgeScaffoldBehavior", 0x001u, false},
	{"BridgeTowerBehavior", 0x006u, false},
	{"BunkerBusterBehavior", 0x003u, false},
	{"CashBountyPower", 0x100u, false},
	{"CashHackSpecialPower", 0x100u, false},
	{"CaveContain", 0x05Fu, false},
	{"CheckpointUpdate", 0x001u, false},
	{"ChinookAIUpdate", 0x001u, true},
	{"CleanupAreaPower", 0x100u, false},
	{"CleanupHazardUpdate", 0x001u, false},
	{"CommandButtonHuntUpdate", 0x001u, false},
	{"CommandSetUpgrade", 0x080u, false},
	{"ConvertToCarBombCrateCollide", 0x010u, false},
	{"ConvertToHijackedVehicleCrateCollide", 0x010u, false},
	{"CostModifierUpgrade", 0x080u, false},
	{"CountermeasuresBehavior", 0x081u, false},
	{"CreateCrateDie", 0x002u, false},
	{"CreateObjectDie", 0x002u, false},
	{"CrushDie", 0x002u, false},
	{"DamDie", 0x002u, false},
	{"DefaultProductionExitUpdate", 0x001u, false},
	{"DefectorSpecialPower", 0x100u, false},
	{"DeletionUpdate", 0x001u, false},
	{"DeliverPayloadAIUpdate", 0x001u, true},
	{"DemoTrapUpdate", 0x001u, false},
	{"DemoralizeSpecialPower", 0x100u, false},
	{"DeployStyleAIUpdate", 0x001u, true},
	{"DestroyDie", 0x002u, false},
	{"DozerAIUpdate", 0x001u, true},
	{"DumbProjectileBehavior", 0x001u, false},
	{"DynamicGeometryInfoUpdate", 0x001u, false},
	{"DynamicShroudClearingRangeUpdate", 0x001u, false},
	{"EMPUpdate", 0x001u, false},
	{"EjectPilotDie", 0x002u, false},
	{"EnemyNearUpdate", 0x001u, false},
	{"ExperienceScalarUpgrade", 0x080u, false},
	{"FXListDie", 0x082u, false},
	{"FireOCLAfterWeaponCooldownUpdate", 0x001u, false},
	{"FireSpreadUpdate", 0x001u, false},
	{"FireWeaponCollide", 0x010u, false},
	{"FireWeaponPower", 0x100u, false},
	{"FireWeaponUpdate", 0x001u, false},
	{"FireWeaponWhenDamagedBehavior", 0x085u, false},
	{"FireWeaponWhenDeadBehavior", 0x082u, false},
	{"FirestormDynamicGeometryInfoUpdate", 0x001u, false},
	{"FlammableUpdate", 0x005u, false},
	{"FlightDeckBehavior", 0x003u, true},
	{"FloatUpdate", 0x001u, false},
	{"GarrisonContain", 0x057u, false},
	{"GenerateMinefieldBehavior", 0x083u, false},
	{"GrantScienceUpgrade", 0x080u, false},
	{"GrantStealthBehavior", 0x001u, false},
	{"GrantUpgradeCreate", 0x008u, false},
	{"HackInternetAIUpdate", 0x001u, true},
	{"HealContain", 0x057u, false},
	{"HealCrateCollide", 0x010u, false},
	{"HeightDieUpdate", 0x001u, false},
	{"HelicopterSlowDeathBehavior", 0x003u, false},
	{"HelixContain", 0x057u, false},
	{"HighlanderBody", 0x020u, false},
	{"HijackerUpdate", 0x001u, false},
	{"HiveStructureBody", 0x020u, false},
	{"HordeUpdate", 0x001u, false},
	{"ImmortalBody", 0x020u, false},
	{"InactiveBody", 0x020u, false},
	{"InstantDeathBehavior", 0x002u, false},
	{"InternetHackContain", 0x057u, false},
	{"JetAIUpdate", 0x001u, true},
	{"JetSlowDeathBehavior", 0x003u, false},
	{"KeepObjectDie", 0x002u, false},
	{"LaserUpdate", 0x800u, false},
	{"LeafletDropBehavior", 0x001u, false},
	{"LifetimeUpdate", 0x001u, false},
	{"LockWeaponCreate", 0x008u, false},
	{"LocomotorSetUpgrade", 0x080u, false},
	{"MaxHealthUpgrade", 0x080u, false},
	{"MinefieldBehavior", 0x017u, false},
	{"MissileAIUpdate", 0x001u, true},
	{"MissileLauncherBuildingUpdate", 0x001u, false},
	{"MobMemberSlavedUpdate", 0x001u, false},
	{"MobNexusContain", 0x057u, false},
	{"ModelConditionUpgrade", 0x080u, false},
	{"MoneyCrateCollide", 0x010u, false},
	{"NeutronBlastBehavior", 0x003u, false},
	{"NeutronMissileSlowDeathBehavior", 0x003u, false},
	{"NeutronMissileUpdate", 0x003u, false},
	{"OCLSpecialPower", 0x100u, false},
	{"OCLUpdate", 0x001u, false},
	{"ObjectCreationUpgrade", 0x080u, false},
	{"OpenContain", 0x057u, false},
	{"OverchargeBehavior", 0x005u, false},
	{"OverlordContain", 0x057u, false},
	{"ParachuteContain", 0x057u, false},
	{"ParkingPlaceBehavior", 0x003u, false},
	{"ParticleUplinkCannonUpdate", 0x001u, false},
	{"PassengersFireUpgrade", 0x080u, false},
	{"PhysicsBehavior", 0x011u, false},
	{"PilotFindVehicleUpdate", 0x001u, false},
	{"PointDefenseLaserUpdate", 0x001u, false},
	{"PoisonedBehavior", 0x005u, false},
	{"PowerPlantUpdate", 0x001u, false},
	{"PowerPlantUpgrade", 0x080u, false},
	{"PreorderCreate", 0x008u, false},
	{"ProductionUpdate", 0x003u, false},
	{"ProjectileStreamUpdate", 0x001u, false},
	{"ProneUpdate", 0x001u, false},
	{"PropagandaTowerBehavior", 0x003u, false},
	{"QueueProductionExitUpdate", 0x001u, false},
	{"RadarUpdate", 0x001u, false},
	{"RadarUpgrade", 0x080u, false},
	{"RadiusDecalUpdate", 0x001u, false},
	{"RailedTransportAIUpdate", 0x001u, true},
	{"RailedTransportContain", 0x057u, false},
	{"RailedTransportDockUpdate", 0x001u, false},
	{"RailroadBehavior", 0x011u, false},
	{"RebuildHoleBehavior", 0x003u, false},
	{"RebuildHoleExposeDie", 0x002u, false},
	{"RepairDockUpdate", 0x001u, false},
	{"ReplaceObjectUpgrade", 0x080u, false},
	{"RiderChangeContain", 0x057u, false},
	{"SabotageCommandCenterCrateCollide", 0x010u, false},
	{"SabotageFakeBuildingCrateCollide", 0x010u, false},
	{"SabotageInternetCenterCrateCollide", 0x010u, false},
	{"SabotageMilitaryFactoryCrateCollide", 0x010u, false},
	{"SabotagePowerPlantCrateCollide", 0x010u, false},
	{"SabotageSuperweaponCrateCollide", 0x010u, false},
	{"SabotageSupplyCenterCrateCollide", 0x010u, false},
	{"SabotageSupplyDropzoneCrateCollide", 0x010u, false},
	{"SalvageCrateCollide", 0x010u, false},
	{"ShroudCrateCollide", 0x010u, false},
	{"SlavedUpdate", 0x001u, false},
	{"SlowDeathBehavior", 0x003u, false},
	{"SmartBombTargetHomingUpdate", 0x001u, false},
	{"SpawnBehavior", 0x007u, false},
	{"SpawnPointProductionExitUpdate", 0x001u, false},
	{"SpecialAbility", 0x100u, false},
	{"SpecialAbilityUpdate", 0x001u, false},
	{"SpecialPowerCompletionDie", 0x002u, false},
	{"SpecialPowerCreate", 0x008u, false},
	{"SpectreGunshipDeploymentUpdate", 0x001u, false},
	{"SpectreGunshipUpdate", 0x001u, false},
	{"SpyVisionSpecialPower", 0x100u, false},
	{"SpyVisionUpdate", 0x081u, false},
	{"SquishCollide", 0x010u, false},
	{"StatusBitsUpgrade", 0x080u, false},
	{"StealthDetectorUpdate", 0x001u, false},
	{"StealthUpdate", 0x001u, false},
	{"StealthUpgrade", 0x080u, false},
	{"StickyBombUpdate", 0x001u, false},
	{"StructureBody", 0x020u, false},
	{"StructureCollapseUpdate", 0x003u, false},
	{"StructureToppleUpdate", 0x003u, false},
	{"SubObjectsUpgrade", 0x080u, false},
	{"SupplyCenterCreate", 0x008u, false},
	{"SupplyCenterDockUpdate", 0x001u, false},
	{"SupplyCenterProductionExitUpdate", 0x001u, false},
	{"SupplyTruckAIUpdate", 0x001u, true},
	{"SupplyWarehouseCreate", 0x008u, false},
	{"SupplyWarehouseCripplingBehavior", 0x005u, false},
	{"SupplyWarehouseDockUpdate", 0x001u, false},
	{"SwayClientUpdate", 0x800u, false},
	{"TechBuildingBehavior", 0x003u, false},
	{"TensileFormationUpdate", 0x001u, false},
	{"ToppleUpdate", 0x011u, false},
	{"TransitionDamageFX", 0x004u, false},
	{"TransportAIUpdate", 0x001u, true},
	{"TransportContain", 0x057u, false},
	{"TunnelContain", 0x05Fu, false},
	{"UndeadBody", 0x020u, false},
	{"UnitCrateCollide", 0x010u, false},
	{"UnpauseSpecialPowerUpgrade", 0x080u, false},
	{"UpgradeDie", 0x002u, false},
	{"VeterancyCrateCollide", 0x010u, false},
	{"VeterancyGainCreate", 0x008u, false},
	{"W3DDebrisDraw", 0x400u, false},
	{"W3DDefaultDraw", 0x400u, false},
	{"W3DDependencyModelDraw", 0x400u, false},
	{"W3DLaserDraw", 0x400u, false},
	{"W3DModelDraw", 0x400u, false},
	{"W3DOverlordAircraftDraw", 0x400u, false},
	{"W3DOverlordTankDraw", 0x400u, false},
	{"W3DOverlordTruckDraw", 0x400u, false},
	{"W3DPoliceCarDraw", 0x400u, false},
	{"W3DProjectileStreamDraw", 0x400u, false},
	{"W3DPropDraw", 0x400u, false},
	{"W3DRopeDraw", 0x400u, false},
	{"W3DScienceModelDraw", 0x400u, false},
	{"W3DSupplyDraw", 0x400u, false},
	{"W3DTankDraw", 0x400u, false},
	{"W3DTankTruckDraw", 0x400u, false},
	{"W3DTracerDraw", 0x400u, false},
	{"W3DTreeDraw", 0x400u, false},
	{"W3DTruckDraw", 0x400u, false},
	{"WanderAIUpdate", 0x001u, true},
	{"WaveGuideUpdate", 0x001u, false},
	{"WeaponBonusUpdate", 0x001u, false},
	{"WeaponBonusUpgrade", 0x080u, false},
	{"WeaponSetUpgrade", 0x080u, false},
	{"WorkerAIUpdate", 0x001u, true},};

// The module type's entry; none for a type the original does not register.
inline const ModuleInterfaces *FindModuleInterfaces(std::string_view type) noexcept
{
	const auto found = std::lower_bound(std::begin(ModuleInterfaceTable), std::end(ModuleInterfaceTable), type,
		[](const ModuleInterfaces &entry, std::string_view key) { return entry.type < key; });
	return found != std::end(ModuleInterfaceTable) && found->type == type ? &*found : nullptr;
}
}
