add_library(generalszh_regeneration_content STATIC)
target_sources(generalszh_regeneration_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES auto_heal_definition.cppm)
target_compile_features(generalszh_regeneration_content PUBLIC cxx_std_23)
target_link_libraries(generalszh_regeneration_content PUBLIC engine_gameplay_regeneration generalszh_content_ini)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set_source_files_properties(auto_heal_definition.test PROPERTIES LANGUAGE CXX)
    add_executable(generalszh_regeneration_content_tests auto_heal_definition.test)
    target_compile_definitions(generalszh_regeneration_content_tests PRIVATE BOOST_TEST_INCLUDED)
    target_link_libraries(generalszh_regeneration_content_tests PRIVATE generalszh_regeneration_content Boost::included_unit_test_framework)
    add_test(NAME generalszh_regeneration_content_tests COMMAND generalszh_regeneration_content_tests)
endif()
