#!/usr/bin/env python3
"""Generates engine/core/math/fixed/angle/FixedAngleTables.cppm (checked in).

atan(2^-i) in turn units (2^32 per full turn), rounded to nearest, computed
once here so the runtime CORDIC never touches floating point.
"""
import math
from pathlib import Path

CORDIC_STEPS = 31
atan = [round(math.atan(2.0 ** -i) / (2 * math.pi) * 2 ** 32) for i in range(CORDIC_STEPS)]
rows = "\n".join("\t" + ", ".join(str(v) for v in atan[i:i + 6]) + "," for i in range(0, len(atan), 6))
out = f"""// Generated by engine/core/math/tools/generate_fixed_angle_tables.py. Do not edit.
module;
#include <array>
#include <cstdint>

export module Engine.Core.Math.FixedAngleTables;

export namespace Engine::Math::Tables
{{
inline constexpr int CordicSteps = {CORDIC_STEPS};
// atan(2^-i) in turn units (2^32 per full turn).
inline constexpr std::array<std::uint32_t, {CORDIC_STEPS}> CordicAtan{{
{rows}
}};
}}
"""
Path(__file__).resolve().parents[1].joinpath("fixed/angle/FixedAngleTables.cppm").write_text(out, newline="\n")
