add_library(generalszh_base_repair_content STATIC)
target_sources(generalszh_base_repair_content PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES base_repair_definition.cppm)
target_compile_features(generalszh_base_repair_content PUBLIC cxx_std_23)
set_property(TARGET generalszh_base_repair_content PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(generalszh_base_repair_content PUBLIC engine_gameplay_rts_repair generalszh_content_ini)
if(RTS_BUILD_ZEROHOUR_EXTRAS)
    find_package(boost_included_unit_test_framework CONFIG REQUIRED)
    set_source_files_properties(base_repair_definition.test PROPERTIES LANGUAGE CXX)
    add_executable(generalszh_base_repair_content_tests base_repair_definition.test)
    target_compile_definitions(generalszh_base_repair_content_tests PRIVATE BOOST_TEST_INCLUDED)
    target_link_libraries(generalszh_base_repair_content_tests PRIVATE generalszh_base_repair_content Boost::included_unit_test_framework)
    add_test(NAME generalszh_base_repair_content_tests COMMAND generalszh_base_repair_content_tests)
endif()
