# Engine fixtures own process-wide singletons. Compare separate Boost processes.
if(NOT DEFINED SCENARIOS)
    set(SCENARIOS simulation ten_thousand)
endif()
foreach(scenario IN LISTS SCENARIOS)
if(scenario STREQUAL "simulation")
    set(expected_frames 2600)
else()
    set(expected_frames 600)
endif()
foreach(mode RANGE 1 3)
    execute_process(COMMAND "${TEST_EXE}" "--run_test=native_${scenario}_serial" --log_level=message
        WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Serial fixture ${mode} failed (${result}):\n${output}\n${error}")
    endif()
    string(REGEX MATCH "Native serial[^\n]+" timing "${output}")
    message(STATUS "${timing}")
    string(REGEX MATCHALL "navigation_frame_crc=[0-9]+:[0-9]+" crcs "${output}")
    list(LENGTH crcs count)
    if(NOT count EQUAL expected_frames)
        message(FATAL_ERROR "Serial fixture ${mode} produced ${count} CRCs")
    endif()
    if(mode EQUAL 1)
        set(reference "${crcs}")
    elseif(NOT "${crcs}" STREQUAL "${reference}")
        math(EXPR final_frame "${expected_frames}-1")
        foreach(frame RANGE 0 ${final_frame})
            list(GET crcs ${frame} actual)
            list(GET reference ${frame} expected)
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "${mode} diverged at frame ${frame}: ${actual}; expected ${expected}")
            endif()
        endforeach()
    endif()
endforeach()
endforeach()
