// Generated by engine/core/math/tools/generate_fixed_angle_tables.py. Do not edit.
module;

export module Engine.Core.Math.FixedAngleTables;
import std;

export namespace Engine::Math::Tables
{
inline constexpr int CordicSteps = 31;
// atan(2^-i) in turn units (2^32 per full turn).
inline constexpr std::array<std::uint32_t, 31> CordicAtan{
	536870912, 316933406, 167458907, 85004756, 42667331, 21354465,
	10679838, 5340245, 2670163, 1335087, 667544, 333772,
	166886, 83443, 41722, 20861, 10430, 5215,
	2608, 1304, 652, 326, 163, 81,
	41, 20, 10, 5, 3, 1,
	1,
};
}
