add_library(engine_gameplay_rts_upgrades STATIC)
target_sources(engine_gameplay_rts_upgrades PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES
	components/upgrade_words.cppm components/upgrade_execution.cppm
	algorithms/upgrade_words.cppm state/upgrade_words.cppm state/upgrade_execution.cppm)
target_compile_features(engine_gameplay_rts_upgrades PUBLIC cxx_std_23)
set_property(TARGET engine_gameplay_rts_upgrades PROPERTY CXX_SCAN_FOR_MODULES ON)
target_link_libraries(engine_gameplay_rts_upgrades PUBLIC engine_ecs)
if(ENGINE_GAMEPLAY_BUILD_TESTS)
	find_package(boost_included_unit_test_framework CONFIG REQUIRED)
	set(upgrade_words_tests components/upgrade_words.test algorithms/upgrade_words.test)
	set_source_files_properties(${upgrade_words_tests} PROPERTIES LANGUAGE CXX)
	add_executable(engine_gameplay_upgrade_words_tests ${upgrade_words_tests})
	set_property(TARGET engine_gameplay_upgrade_words_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(engine_gameplay_upgrade_words_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(engine_gameplay_upgrade_words_tests PRIVATE engine_gameplay_rts_upgrades Boost::included_unit_test_framework)
	add_test(NAME engine_gameplay_upgrade_words_tests COMMAND engine_gameplay_upgrade_words_tests)
	set_source_files_properties(components/upgrade_execution.test PROPERTIES LANGUAGE CXX)
	add_executable(engine_gameplay_upgrade_execution_tests components/upgrade_execution.test)
	set_property(TARGET engine_gameplay_upgrade_execution_tests PROPERTY CXX_SCAN_FOR_MODULES ON)
	target_compile_definitions(engine_gameplay_upgrade_execution_tests PRIVATE BOOST_TEST_INCLUDED)
	target_link_libraries(engine_gameplay_upgrade_execution_tests PRIVATE engine_gameplay_rts_upgrades Boost::included_unit_test_framework)
	add_test(NAME engine_gameplay_upgrade_execution_tests COMMAND engine_gameplay_upgrade_execution_tests)
endif()
