add_subdirectory(economy)
add_subdirectory(unlocks)
add_subdirectory(bounty)
add_subdirectory(rank)
add_subdirectory(visibility)
add_subdirectory(power)
add_subdirectory(radar)
add_subdirectory(production)
add_subdirectory(upgrades)
add_subdirectory(match)
add_subdirectory(orders)
add_subdirectory(harvesting)
add_subdirectory(construction)
add_subdirectory(repair)
add_subdirectory(ai)
